# Generated by Django 3.2.23 on 2023-12-19 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_categories', models.ManyToManyField(related_name='_core_category_sub_categories_+', to='core.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='aiblog',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='aicommunities',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='aisolutions',
            name='categories',
        ),
        migrations.RenameModel(
            old_name='AIPost',
            new_name='Entry',
        ),
        migrations.DeleteModel(
            name='AI',
        ),
        migrations.DeleteModel(
            name='AIBlog',
        ),
        migrations.DeleteModel(
            name='AICommunities',
        ),
        migrations.DeleteModel(
            name='AISolutions',
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ManyToManyField(to='core.Category'),
        ),
    ]
