# Generated by Django 3.2.23 on 2023-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231219_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_categories',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('categories', models.ManyToManyField(to='core.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ManyToManyField(to='core.SubCategory'),
        ),
    ]
